CREATE TABLE IF NOT EXISTS dwd_en_project (
    `id` VARCHAR(64) NOT NULL COMMENT '项目记录的唯一主键标识。',
    `project_number` VARCHAR(32) COMMENT '项目在管理系统中的编号。',
    `title` VARCHAR(512) COMMENT '项目的名称或标题。',
    `project_source` VARCHAR(64) COMMENT '项目所属的资助来源或立项来源。',
    `funded_institution` VARCHAR(128) COMMENT '获得项目资助的机构名称。',
    `project_level` ENUM('国家级', '州级', '市级', '县级', '其他') COMMENT '项目所属的级别或层次。',
    `funded_amount` DECIMAL(18,2) COMMENT '项目获得的资助经费金额，单位为美元。',
    `discipline` VARCHAR(256) COMMENT '项目所属的学科领域。',
    `discipline_code` VARCHAR(256) COMMENT '项目所属学科的分类代码。',
    `fund_category` VARCHAR(64) COMMENT '项目对应的基金或资助类别。',
    `funded_region` VARCHAR(32) COMMENT '项目受资助机构所在的地区信息。',
    `participating_institution` JSON COMMENT '参与项目研究或实施的机构信息。',
    `approval_year` INT COMMENT '项目获批立项的年份。',
    `approval_time` DATE COMMENT '项目正式获批立项的时间。',
    `research_period` VARCHAR(64) COMMENT '项目计划开展研究的时间期限。',
    `project_host` VARCHAR(64) COMMENT '项目的主要负责人或主持人。',
    `participants` JSON COMMENT '参与项目研究或实施的人员信息。',
    `keywords` JSON COMMENT '描述项目研究主题的关键词。',
    `abstract` LONGTEXT COMMENT '项目申请书或标书中的摘要内容。',
    `final_report_abstract` LONGTEXT COMMENT '项目结题报告中的摘要内容。',
    `project_page_url` TEXT COMMENT '项目详情页面的访问链接。',
    `updated_time` DATETIME NOT NULL COMMENT '该条数据最近一次更新的时间。',
    PRIMARY KEY (`id`),
    KEY `idx_project_number` (`project_number`),
    KEY `idx_discipline_code` (`discipline_code`),
    KEY `idx_approval_year` (`approval_year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='国外项目信息表';
