CREATE TABLE `ods_en_project_output` (
  `id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'UUID主键',
  `total_outputs` int DEFAULT NULL COMMENT '项目总产出数量',
  `journal_articles_count` int DEFAULT NULL COMMENT '期刊文章数量',
  `conference_papers_count` int DEFAULT NULL COMMENT '会议论文数量',
  `books_count` int DEFAULT NULL COMMENT '图书专著数量',
  `degree_papers_count` int DEFAULT NULL COMMENT '学位论文数量',
  `patents_count` int DEFAULT NULL COMMENT '专利数量',
  `clinical_trials_count` int DEFAULT NULL COMMENT '临床试验数量',
  `products_count` int DEFAULT NULL COMMENT '产品数量',
  `awards_count` int DEFAULT NULL COMMENT '奖项数量',
  `reports_count` int DEFAULT NULL COMMENT '报告数量',
  `other_outputs_count` int DEFAULT NULL COMMENT '其他产出数量',
  `output_journal_articles` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '期刊文章',
  `output_conference_papers` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '会议论文',
  `output_books` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '图书专著',
  `output_degree_papers` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '学位论文',
  `output_patents` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '专利',
  `output_clinical_trials` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '临床试验',
  `output_products` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '产品',
  `output_awards` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '奖项',
  `output_reports` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '报告',
  `output_other` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '其他成果',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='深势-国外项目产出信息表';
