"""平台首页总览假数据服务。"""

from biz.schemas.platform_overview import (
    AssetChangeRow,
    AssetOverviewGroup,
    LatestChange,
    ManagementRisk,
    PlatformOverviewData,
    StructureItem,
)


class PlatformOverviewService:
    """返回首页当前使用的演示数据，不依赖数据库或图服务。"""

    def get_overview(self) -> PlatformOverviewData:
        return PlatformOverviewData(
            platform_status="平台服务正常",
            pending_batch_count=2,
            updated_at="10:30",
            asset_overview_groups=[
                AssetOverviewGroup(
                    key="entity",
                    title="实体数据",
                    total="1.28 亿",
                    total_label="实体总量",
                    added="+1,183.6 万",
                    added_label="今日新增",
                ),
                AssetOverviewGroup(
                    key="relation",
                    title="关系数据",
                    total="6.42 亿",
                    total_label="关系总量",
                    added="+2,040 万",
                    added_label="今日新增",
                ),
                AssetOverviewGroup(
                    key="property",
                    title="属性值数据",
                    total="18.76 亿",
                    total_label="属性值总量",
                    added="+3,264 万",
                    added_label="今日新增及更新",
                ),
            ],
            asset_change_rows={
                "entity": [
                    AssetChangeRow(
                        type="机构 / 企业",
                        object="华南智能芯片有限公司",
                        change="新增 Organization",
                        source="enterprise_profile",
                        time="10:30:13",
                    ),
                    AssetChangeRow(
                        type="专家 / 人才",
                        object="周启航",
                        change="新增 Expert",
                        source="expert_profile",
                        time="10:30:18",
                    ),
                    AssetChangeRow(
                        type="论文成果",
                        object="《多模态大模型知识推理方法研究》",
                        change="新增 Paper",
                        source="paper_record",
                        time="10:30:21",
                    ),
                    AssetChangeRow(
                        type="产品 / 技术产品",
                        object="边缘推理芯片 X7",
                        change="新增 Product",
                        source="enterprise_product",
                        time="10:30:26",
                    ),
                ],
                "relation": [
                    AssetChangeRow(
                        type="任职关系",
                        object="周启航 → 中国科学院自动化研究所",
                        change="新增 WORKS_AT",
                        source="expert_employment",
                        time="10:30:22",
                    ),
                    AssetChangeRow(
                        type="成果关系",
                        object="周启航 → 多模态大模型知识推理方法研究",
                        change="新增 PUBLISH",
                        source="paper_author",
                        time="10:30:25",
                    ),
                    AssetChangeRow(
                        type="产品关系",
                        object="华南智能芯片 → 边缘推理芯片 X7",
                        change="新增 HAS_PRODUCT",
                        source="enterprise_product",
                        time="10:30:29",
                    ),
                ],
                "property": [
                    AssetChangeRow(
                        type="企业属性",
                        object="华南智能芯片·注册资本",
                        change="新增 registered_capital",
                        source="enterprise_profile",
                        time="10:30:14",
                    ),
                    AssetChangeRow(
                        type="企业属性",
                        object="华南智能芯片·上市状态",
                        change="更新 listing_status",
                        source="enterprise_profile",
                        time="10:30:16",
                    ),
                    AssetChangeRow(
                        type="论文属性",
                        object="P202607140018·发表时间",
                        change="新增 publish_date",
                        source="paper_record",
                        time="10:30:23",
                    ),
                    AssetChangeRow(
                        type="关系属性",
                        object="WORKS_AT_20418·置信度",
                        change="更新 confidence",
                        source="graph_alignment",
                        time="10:30:31",
                    ),
                ],
            },
            latest_changes=[
                LatestChange(
                    time="10:30",
                    type="更新",
                    domain="机构域",
                    title="清华大学机构属性更新完成",
                    detail="机构简称与统一标识已完成标准化更新",
                    impact="处理实例 PI-20260714-0002",
                    to="/processing-instance/PI-20260714-0002",
                ),
                LatestChange(
                    time="10:18",
                    type="对齐",
                    domain="人才域",
                    title="陈卓候选专家实体完成对齐",
                    detail="机构别名经人工确认后，候选实体已合并至标准专家实体",
                    impact="处理实例 PI-20260713-0008",
                    to="/processing-instance/PI-20260713-0008",
                ),
                LatestChange(
                    time="10:13",
                    type="新增",
                    domain="人才域",
                    title="张明远标准专家实体构建完成",
                    detail="完成来源读取、Schema 映射、实体标准化与图谱入库",
                    impact="处理实例 PI-20260714-0001",
                    to="/processing-instance/PI-20260714-0001",
                ),
                LatestChange(
                    time="09:48",
                    type="质量",
                    domain="论文域",
                    title="重复论文成果记录等待确认",
                    detail="同一 paper_id 对应三条来源记录，需要人工确认主记录",
                    impact="处理实例 PI-20260714-0007",
                    to="/processing-instance/PI-20260714-0007",
                ),
                LatestChange(
                    time="昨日",
                    type="Schema",
                    domain="全域",
                    title="统一 Schema v1.8 已发布",
                    detail="确认 11 个首版必落实体、42 个标准事实关系和 9 类候选实体",
                    impact="所有新建批次使用 v1.8",
                    to="/schema",
                ),
            ],
            management_risks=[
                ManagementRisk(
                    title="大模型抽取流程已阻断",
                    detail="PI-20260714-0101 · 326 条受影响 · 张建图",
                    detail_to="/processing-instance/PI-20260714-0101",
                    review_to="/manual-review/task/PI-20260714-0101",
                ),
                ManagementRisk(
                    title="Schema 批量映射失败",
                    detail="PI-20260714-0102 · 1,284 条任务受影响 · 张建图",
                    detail_to="/processing-instance/PI-20260714-0102",
                    review_to="/manual-review/task/PI-20260714-0102",
                ),
                ManagementRisk(
                    title="张明远候选实体存在冲突",
                    detail="PI-20260714-0004 · 实体对齐 · 王审核",
                    detail_to="/processing-instance/PI-20260714-0004",
                    review_to="/manual-review/task/PI-20260714-0004",
                ),
            ],
            entity_structure=[
                StructureItem(
                    label="专家 / 人才",
                    schema="Expert",
                    count="4,286 万",
                    ratio=34,
                    tone="#2e90fa",
                ),
                StructureItem(
                    label="论文成果",
                    schema="Paper",
                    count="2,931 万",
                    ratio=23,
                    tone="#7a5af8",
                ),
                StructureItem(
                    label="机构 / 企业",
                    schema="Organization",
                    count="2,164 万",
                    ratio=17,
                    tone="#12b76a",
                ),
                StructureItem(
                    label="项目 / 专利",
                    schema="Project / Patent",
                    count="1,438 万",
                    ratio=11,
                    tone="#f79009",
                ),
                StructureItem(
                    label="其他实体",
                    schema="Event / Product / Field",
                    count="1,901 万",
                    ratio=15,
                    tone="#98a2b3",
                ),
            ],
            relation_structure=[
                StructureItem(
                    label="发表 / 引用 / 成果",
                    schema="PUBLISH / CITES / OUTPUT",
                    count="2.04 亿",
                    ratio=32,
                    tone="#165dff",
                ),
                StructureItem(
                    label="任职 / 就读 / 作者单位",
                    schema="WORKS_AT / STUDY_AT",
                    count="1.28 亿",
                    ratio=20,
                    tone="#2e90fa",
                ),
                StructureItem(
                    label="项目 / 专利参与",
                    schema="LEAD_PROJECT / INVENT_PATENT",
                    count="1.16 亿",
                    ratio=18,
                    tone="#06aed4",
                ),
                StructureItem(
                    label="企业 / 产品 / 事件",
                    schema="HAS_PRODUCT / HAS_EVENT",
                    count="0.92 亿",
                    ratio=14,
                    tone="#7a5af8",
                ),
                StructureItem(
                    label="其他关系",
                    schema="产业链 / 推理关系",
                    count="1.02 亿",
                    ratio=16,
                    tone="#98a2b3",
                ),
            ],
        )
