"""Schema 管理页面对应的系统 Schema 初始化目录。"""

from __future__ import annotations

CHAIN_NODE_PRIMARY_KEY = "chain_code + node_id"
EXPERT_PERSON_TYPE = "Expert / Person"
ORGANIZATION_PERSON_TYPE = "Organization / Person"

ENTITY_SPECS = [
    (
        "Expert",
        "专家 / 人才 / 学者",
        True,
        "scholar_id / expert_id",
        "dwd_scholar / dwd_paper_author / dwd_project_person / dwd_patent_inventor",
        "统一承载科研与产业人才主体",
    ),
    (
        "Organization",
        "机构 / 企业",
        True,
        "org_id / external_id / credit_code",
        "dwd_org_reg_info / dwd_forg_base_info / dwd_paper_affiliation / dwd_patent_applicant",
        "高校、科研机构、企业、医院和政府机构统一建模，用 org_category 区分",
    ),
    (
        "Paper",
        "论文",
        True,
        "DOI / paper_id",
        "dwd_zh_paper_detail / dwd_en_paper_detail / dwd_paper_reference",
        "论文成果与引用信息",
    ),
    (
        "Project",
        "项目",
        True,
        "id / project_number",
        "dwd_zh_project / dwd_en_project / dwd_project_output",
        "科研项目、资助、参与人员与项目成果",
    ),
    (
        "Patent",
        "专利",
        True,
        "patent_id / publication_number / application_number",
        "dwd_patent / dwd_patent_inventor / dwd_patent_applicant",
        "专利成果、法律状态、权利人与技术分类",
    ),
    (
        "Report",
        "报告",
        True,
        "report_id",
        "dwd_zh_report / dwd_en_report / dwd_report_author",
        "科技报告及其作者、机构、论文和项目关联",
    ),
    (
        "Policy",
        "政策",
        True,
        "id / recordId / URL",
        "dws_zck_policy / dwd_zck_intl_policy / dwd_policy_department",
        "政策文本、发布部门、领域与产业链节点",
    ),
    (
        "Event",
        "事件 / 资讯",
        True,
        "news_id / URL / 生成 ID",
        "dwd_org_important_news_info / dwd_industry_chain_news_info / dwd_financing_event",
        "用 event_type 区分资讯、融资、投资、并购、政策等事件",
    ),
    (
        "IndustryChainNode",
        "产业链节点",
        True,
        CHAIN_NODE_PRIMARY_KEY,
        "dwd_industry_chain_info",
        "产业链的上游、中游、下游及具体环节",
    ),
    (
        "Product",
        "产品 / 技术产品",
        True,
        "产品 ID / 标准产品名",
        "dwd_org_industry_chain_prod_dtl",
        "企业产品、技术产品与产业链节点",
    ),
    (
        "ResearchField",
        "研究方向 / 技术领域",
        True,
        "field_id / discipline_code / 标准名",
        "dim_research_field / dim_discipline_code / dim_ipc",
        "统一研究方向、学科、关键词、IPC 与产业技术领域",
    ),
    (
        "Person",
        "通用人员",
        False,
        "person_id",
        "dwd_org_executive / dwd_org_shareholder / dwd_patent_inventor / dwd_paper_author",
        "已确认为同一自然人，但不能确认为专家时使用",
    ),
    (
        "Publication",
        "期刊 / 会议 / 出版物",
        False,
        "ISSN / EISSN / publication_id",
        "dim_publication / dwd_journal",
        "论文发表载体及其动态指标",
    ),
    (
        "IndustryChain",
        "产业链",
        False,
        "chain_code",
        "dim_industry_chain / dwd_industry_chain_info",
        "表示整条产业链，与 IndustryChainNode 明确分层",
    ),
]

ATTRIBUTE_SPECS = {
    "Expert": (
        "expert_id",
        "name_zh, name_en, avatar, organization_name_zh, bio_zh, bio_en",
        "paper_count, citation_count, h_index",
        "dwd_scholar",
    ),
    "Organization": (
        "org_id",
        "name_zh, name_en, external_id, org_category, province, city, address",
        "listing_status, registered_capital_value, financial_metrics",
        "dwd_org_reg_info / dwd_forg_base_info",
    ),
    "Paper": (
        "paper_id",
        "doi, title_zh, title_en, publish_year, abstract_zh, abstract_en, keywords",
        "citation_count, is_open_access",
        "dwd_zh_paper_detail / dwd_en_paper_detail",
    ),
    "Project": (
        "project_id",
        "project_number, title, project_source, project_level, discipline_code, approval_time",
        "funded_amount, research_period",
        "dwd_zh_project / dwd_en_project",
    ),
    "Patent": (
        "patent_id",
        "publication_number, application_number, country_code, application_date, ipc_main, cpc_main",
        "legal_status, cited_by_nums, anticipated_expiration",
        "dwd_patent",
    ),
    "Report": (
        "report_id",
        "title_zh, title_en, authors_raw, organization_raw, abstract_zh, keywords_zh",
        "publication_date, preparation_time",
        "dwd_zh_report / dwd_en_report",
    ),
    "Policy": (
        "policy_id",
        "title, content, url, issueno, pubtime, region, keywords, publish_department",
        "按政策源更新",
        "dws_zck_policy / dwd_zck_intl_policy",
    ),
    "Event": (
        "event_id",
        "event_type, title, event_time, summary, source_url, subject",
        "event_heat, impact_score",
        "dwd_industry_chain_news_info / dwd_org_important_news_info",
    ),
    "IndustryChainNode": (
        CHAIN_NODE_PRIMARY_KEY,
        "node_name, node_type, level, parent_id, node_stage",
        "chain_score",
        "dwd_industry_chain_info",
    ),
    "Product": (
        "product_id / 标准名",
        "product_name, product_seq, company_name, credit_code",
        "所属节点和企业映射",
        "dwd_org_industry_chain_prod_dtl",
    ),
    "ResearchField": (
        "field_id / discipline_code",
        "standard_name, alias, field_type, parent_field",
        "别名与上下位字典",
        "dim_research_field / dim_discipline_code",
    ),
}

FACT_RELATION_SPECS = [
    ("HAS_RESEARCH_FIELD", "专家研究方向", "Expert", "ResearchField", "专家方向拆分、标准化"),
    ("PUBLISH", "发表论文", "Expert", "Paper", "作者对齐后生成，保留作者顺序"),
    ("WORKS_AT", "任职", EXPERT_PERSON_TYPE, "Organization", "工作经历抽取机构、职位和时间"),
    ("STUDY_AT", "就读", EXPERT_PERSON_TYPE, "Organization", "教育背景抽取学校、专业、学历和时间"),
    (
        "AFFILIATED_WITH",
        "作者发表时单位",
        EXPERT_PERSON_TYPE,
        "Organization",
        "论文作者单位对齐后生成",
    ),
    ("PUBLISHED_IN", "论文发表于", "Paper", "Publication", "ISSN、EISSN 或出版物名对齐"),
    ("CITES", "论文引用", "Paper", "Paper", "DOI、论文 ID 或题名作者对齐"),
    ("REFERENCES", "论文参考", "Paper", "Paper", "参考文献对齐后生成"),
    ("PAPER_FIELD", "论文研究方向", "Paper", "ResearchField", "关键词与学科分类归一"),
    (
        "SHAREHOLDER_OF",
        "股东关系",
        ORGANIZATION_PERSON_TYPE,
        "Organization",
        "股东名称对齐，保留持股比例",
    ),
    ("SUBSIDIARY_OF", "子公司关系", "Organization", "Organization", "子公司对齐后生成"),
    ("EXECUTIVE_OF", "高管任职", EXPERT_PERSON_TYPE, "Organization", "高管姓名、职务和机构对齐"),
    ("HAS_PRODUCT", "企业拥有产品", "Organization", "Product", "产品拆分、标准化后生成"),
    ("HAS_EVENT", "主体发生事件", "Organization", "Event", "企业与资讯、融资、并购等事件连接"),
    ("LEAD_PROJECT", "主持项目", "Expert", "Project", "项目主持人对齐后生成"),
    ("PARTICIPATE_IN", "参与项目", EXPERT_PERSON_TYPE, "Project", "参与者拆分对齐后生成"),
    ("FUNDED_BY", "项目受资助", "Project", "Organization", "资助机构对齐后生成"),
    (
        "PARTICIPATE_IN_PROJECT",
        "机构参与项目",
        "Organization",
        "Project",
        "参与机构拆分对齐后生成",
    ),
    ("PROJECT_FIELD", "项目研究方向", "Project", "ResearchField", "学科代码优先，关键词辅助"),
    ("PROJECT_OUTPUT_PAPER", "项目产出论文", "Project", "Paper", "DOI 或 paper_id 对齐"),
    ("PROJECT_OUTPUT_PATENT", "项目产出专利", "Project", "Patent", "专利号或 patent_id 对齐"),
    ("PROJECT_OUTPUT_REPORT", "项目产出报告", "Project", "Report", "报告对齐后生成"),
    ("INVENT_PATENT", "发明专利", EXPERT_PERSON_TYPE, "Patent", "发明人对齐后生成"),
    ("APPLY_PATENT", "申请专利", ORGANIZATION_PERSON_TYPE, "Patent", "申请人对齐后生成"),
    ("OWN_PATENT", "拥有专利", ORGANIZATION_PERSON_TYPE, "Patent", "当前权利人对齐后生成"),
    ("PATENT_FIELD", "专利技术方向", "Patent", "ResearchField", "IPC / IPCR / CPC 分类标准化"),
    ("PATENT_CITES", "专利引用", "Patent", "Patent", "被引用专利对齐后生成"),
    ("AUTHOR_OF_REPORT", "报告作者", EXPERT_PERSON_TYPE, "Report", "报告作者对齐后生成"),
    ("REPORT_ORG", "报告机构", "Report", "Organization", "完成单位对齐后生成"),
    ("REPORT_RELATED_PAPER", "报告关联论文", "Report", "Paper", "相关文献对齐"),
    ("REPORT_RELATED_PROJECT", "报告关联项目", "Report", "Project", "相关项目对齐"),
    ("REPORT_FIELD", "报告研究方向", "Report", "ResearchField", "关键词标准化"),
    ("POLICY_RELATED_FIELD", "政策关联领域", "Policy", "ResearchField", "关键词、全要素和正文抽取"),
    (
        "POLICY_RELATED_CHAIN_NODE",
        "政策关联产业链节点",
        "Policy",
        "IndustryChainNode",
        "关键词与语义匹配",
    ),
    ("POLICY_PUBLISHED_BY", "政策发布部门", "Policy", "Organization", "发布部门对齐后生成"),
    (
        "HAS_CHAIN_NODE",
        "产业链包含节点",
        "IndustryChain",
        "IndustryChainNode",
        CHAIN_NODE_PRIMARY_KEY,
    ),
    (
        "PARENT_OF",
        "产业链父子节点",
        "IndustryChainNode",
        "IndustryChainNode",
        "parent_id 指向 node_id",
    ),
    (
        "UPSTREAM_DOWNSTREAM",
        "产业链上下游",
        "IndustryChainNode",
        "IndustryChainNode",
        "downstream_link_code 生成",
    ),
    (
        "BELONGS_TO_CHAIN_NODE",
        "企业属于产业链节点",
        "Organization",
        "IndustryChainNode",
        "企业对齐后保留 chain_score",
    ),
    (
        "PRODUCT_CHAIN_NODE",
        "产品关联产业链节点",
        "Product",
        "IndustryChainNode",
        "标准产品连接所属节点",
    ),
    (
        "RELATED_EVENT",
        "产业链节点关联事件",
        "IndustryChainNode",
        "Event",
        "产业链资讯生成事件",
    ),
    (
        "ORG_FIELD",
        "企业技术领域",
        "Organization",
        "ResearchField",
        "行业分类、经营范围和产品领域归一",
    ),
    (
        "HAS_FINANCIAL_RECORD",
        "机构年度财务",
        "Organization",
        "FinancialRecord",
        "需要保留年度历史时生成",
    ),
    (
        "BELONGS_TO_PATENT_FAMILY",
        "专利属于家族",
        "Patent",
        "PatentFamily",
        "专利家族对齐后生成",
    ),
]

INFERRED_RELATION_SPECS = [
    ("CO_AUTHOR", "论文合作", "Expert", "Expert", "共同发表同一论文"),
    ("COLLEAGUE", "同事关系", "Expert", "Expert", "同一机构任职且时间重叠，或共同参与项目"),
    ("ALUMNI", "校友关系", "Expert", "Expert", "同校就读，结合专业、学历和时间"),
    (
        "DIRECT_RELATION",
        "专家直接关系",
        "Expert",
        "Expert",
        "论文、项目、专利、同事、校友和企业合作综合判定",
    ),
    ("INDIRECT_RELATION", "专家间接关系", "Expert", "其他实体", "基于标准事实关系做多跳路径分析"),
    (
        "COOPERATIVE_OUTPUT",
        "合作成果",
        "Expert",
        "Achievement 视图",
        "共同论文、专利、项目和报告统计",
    ),
    (
        "EXPERT_COMPANY_RELATION",
        "专家企业关系",
        "Expert",
        "Organization",
        "任职、专利、项目、高管与产品领域综合判定",
    ),
    (
        "CHAIN_EVENT_IMPACT",
        "产业链事件影响",
        "IndustryChainNode",
        "Event",
        "事件热度、关联企业数、政策影响和趋势",
    ),
    (
        "CHAIN_OVERVIEW_RELATION",
        "产业链全景关联",
        "IndustryChainNode",
        "多类实体",
        "节点、企业、产品、专家、政策和事件综合关联",
    ),
]
