CREATE TABLE IF NOT EXISTS `kg_schema_script_validation` (
  `id` VARCHAR(36) NOT NULL,
  `operation` VARCHAR(32) NOT NULL,
  `schema_id` VARCHAR(36) NULL,
  `metadata_json` TEXT NULL,
  `bucket` VARCHAR(128) NOT NULL,
  `object_key` VARCHAR(512) NOT NULL,
  `original_filename` VARCHAR(255) NOT NULL,
  `content_type` VARCHAR(128) NOT NULL,
  `size_bytes` BIGINT NOT NULL,
  `etag` VARCHAR(128) NULL,
  `sha256` VARCHAR(64) NOT NULL,
  `uploaded_by` VARCHAR(128) NOT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'queued',
  `stage` VARCHAR(32) NOT NULL DEFAULT 'queued',
  `progress` INT NOT NULL DEFAULT 5,
  `message` VARCHAR(1000) NOT NULL DEFAULT '',
  `summary` TEXT NOT NULL,
  `issues_json` TEXT NOT NULL,
  `result_json` TEXT NULL,
  `result_schema_id` VARCHAR(36) NULL,
  `error_code` VARCHAR(64) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `started_at` DATETIME NULL,
  `completed_at` DATETIME NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_kg_schema_script_validation_user_created` (`uploaded_by`, `created_at`),
  KEY `idx_kg_schema_script_validation_status_updated` (`status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Schema 脚本 LLM 安全校验任务'
