CREATE TABLE `dwd_author_info` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `auid` bigint NOT NULL COMMENT '作者唯一ID',
  `orcid` varchar(64) DEFAULT NULL COMMENT 'ORCID 标识',
  `orcid_matching_type` varchar(64) DEFAULT NULL COMMENT 'ORCID匹配类型',
  `given_name` varchar(255) DEFAULT NULL COMMENT '名',
  `surname` varchar(255) DEFAULT NULL COMMENT '姓',
  `indexed_name` varchar(255) DEFAULT NULL COMMENT '索引名称',
  `initials` varchar(32) DEFAULT NULL COMMENT '姓名缩写',
  `alias_status` varchar(32) DEFAULT NULL COMMENT '别名状态',
  `name_variants` varchar(500) DEFAULT NULL COMMENT '姓名别名列表（逗号分隔）',
  `history_ids` varchar(500) DEFAULT NULL COMMENT '历史ID列表（逗号分隔）',
  `email` varchar(255) DEFAULT NULL COMMENT '邮箱',
  `email_type` varchar(32) DEFAULT NULL COMMENT '邮箱类型',
  `asjc_list` varchar(500) DEFAULT NULL COMMENT 'ASJC学科代码列表，逗号分隔',
  `asjc_freq_list` varchar(500) DEFAULT NULL COMMENT 'ASJC频次列表，逗号分隔',
  `subjabbr_list` varchar(500) DEFAULT NULL COMMENT '学科缩写列表，逗号分隔',
  `subjabbr_freq_list` varchar(500) DEFAULT NULL COMMENT '学科缩写频次，逗号分隔',
  `n_affiliation_current` int DEFAULT '0' COMMENT '当前机构数量',
  `current_affiliations` varchar(500) DEFAULT NULL COMMENT '当前有效机构ID列表，逗号分隔',
  `current_affiliations_parent` varchar(500) DEFAULT NULL COMMENT '父机构ID列表，逗号分隔',
  `corrupt_xml` tinyint DEFAULT '0' COMMENT 'XML文件是否损坏（1=损坏，0=正常）',
  `xmlsize` int DEFAULT NULL COMMENT 'XML文件大小',
  `datetime_max` varchar(32) DEFAULT NULL COMMENT '数据最新日期',
  `suppress` tinyint DEFAULT '0' COMMENT '是否隐藏',
  `type` varchar(32) DEFAULT NULL COMMENT '作者类型',
  `curated` tinyint DEFAULT '0' COMMENT '是否经过人工校准',
  `curtype` varchar(255) DEFAULT NULL COMMENT '校准类型',
  `cur_source` varchar(255) DEFAULT NULL COMMENT '校准来源',
  `cur_timestamp` varchar(255) DEFAULT NULL COMMENT '校准时间戳',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '入库时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_auid` (`auid`)
) ENGINE=InnoDB AUTO_INCREMENT=1001 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Scopus作者元数据表';
