CREATE TABLE IF NOT EXISTS dwd_forg_base_info (
    `org_id` VARCHAR(255) NOT NULL COMMENT '机构id',
    `name_en` VARCHAR(255) NOT NULL COMMENT '机构名称',
    `name_alias` VARCHAR(255) COMMENT '机构本地名称',
    `country_code` VARCHAR(255) COMMENT '国家代码',
    `country` VARCHAR(255) COMMENT '国家',
    `external_id` TEXT COMMENT '当地官方唯一注册码',
    `city` VARCHAR(255) COMMENT '所在城市',
    `address` TEXT COMMENT '公司地址',
    `postal_code` TEXT COMMENT '邮政编码（无数据）',
    `phone` VARCHAR(255) COMMENT '联系电话',
    `email` VARCHAR(255) COMMENT '电子邮箱',
    `company_type` TEXT COMMENT '企业类型',
    `registration_org` TEXT COMMENT '注册机构（无数据）',
    `incorporation_year` BIGINT COMMENT '成立年份',
    `incorporation_date` DATE COMMENT '成立日期/注册日期/核准日期',
    `listing_status` VARCHAR(255) COMMENT '上市状态',
    `registered_capital_value` BIGINT COMMENT '注册资本',
    `registered_capital_currency_code` VARCHAR(255) COMMENT '注册资本货币代码',
    `industry_class` VARCHAR(255) COMMENT '公司行业分类',
    `industry_type` VARCHAR(255) COMMENT '行业分类标准（新增字段）'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='海外机构基本信息';
