CREATE TABLE `ods_en_report` (
  `Identifier_ID` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Report_Num` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Title_Title` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Title_AlterNativeTitle` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Creator_Creator` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Creator_AlterNativeCreator` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Creator_Org` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Creator_AlterNativeOrg` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Date_Issued` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Description_Abstract` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_AlternativeAbstract` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Subject_Keywords` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Subject_AlternativeKeywords` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Subject_CLC` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Subject_SelfFL` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Report_Source` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Language_Language` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Place_Counry` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Source_Page` varchar(512) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Source_PageCount` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Yn_publition` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Report_Type` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Publisher_Publisher` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `f_id` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Date_Download` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `DataLink` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Collection_Number` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Document_Type` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Sponsor` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `IS_OA` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_Publish_Date` varchar(512) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_FulltextUrl` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='万方外文报告信息';
