CREATE TABLE `ods_zh_report` (
  `title` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `alternativeTitle` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `creator` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `creatOrorganization` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `prepareOrganization` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `publicScope` int DEFAULT NULL,
  `publicDate` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `delaypubliclyYears` int DEFAULT NULL,
  `note` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `abstractCn` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `proposalDate` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `downtime` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `keywordsCn` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `keywordsEn` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `abstractEn` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `projectName` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `projectSubjectName` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `competentOrg` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `responsiblePerson` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `startDate` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `endDate` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `linkmanName` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `linkmanEmail` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `lnkmanPhone` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `linkmanAddresss` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `fieldId` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `classification` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `kjbgType` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `ID` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='万方中文报告信息';
