CREATE TABLE IF NOT EXISTS dwd_en_paper (
    `paper_id` VARCHAR(64) NOT NULL COMMENT '文献记录的唯一主键标识。',
    `doi` VARCHAR(512) NOT NULL COMMENT '论文的唯一标识编码。',
    `name_en` VARCHAR(1024) COMMENT '文献的英文标题名称。',
    `name_zh` VARCHAR(1024) COMMENT '文献的中文标题名称。',
    `publication_id` BIGINT NOT NULL COMMENT '关联出版物的id，用于获取期刊详情信息',
    `paper_type` VARCHAR(255) COMMENT '文献所属出版物的章节名称，栏目等。',
    `publication_type` VARCHAR(255) COMMENT '标识出版载体的类型，如期刊、会议或预印本等。',
    `publication_name_en` VARCHAR(1024) COMMENT '期刊、顶会或预印本平台的英文名称。',
    `issn` VARCHAR(16) COMMENT '期刊的国际标准连续出版物编号。纸印出版 issn',
    `eissn` VARCHAR(16) COMMENT '期刊的国际标准连续出版物编号。在网发行 issn',
    `volume` VARCHAR(128) COMMENT '文献发表所在期刊的卷号。',
    `issue` VARCHAR(128) COMMENT '文献发表所在期刊的期号。',
    `first_page` VARCHAR(255) COMMENT '论文在期刊中的起始页码。',
    `last_page` VARCHAR(255) COMMENT '论文在期刊中的结束页码。',
    `publication_year` YEAR COMMENT '文献正式发表的年份。',
    `publication_date` VARCHAR(255) COMMENT '文献正式发表的时间。',
    `language` VARCHAR(255) COMMENT '文献或期刊出版使用的语言类型。',
    `abstract_available` VARCHAR(1) COMMENT '摘要是否可用。',
    `open_access` TINYINT COMMENT '标识期刊或论文是否为开放获取。',
    `paper_url` TEXT COMMENT '文献在官网或来源平台中的访问链接。',
    `data_source` VARCHAR(255) NOT NULL COMMENT '来源贴源库表名',
    `created_time` DATETIME NOT NULL COMMENT '数据在要素库中的创建时间。',
    `updated_time` DATETIME NOT NULL COMMENT '该条数据最近一次更新的时间。',
    KEY `idx_01_paper_id` (`paper_id`),
    KEY `idx_01_doi` (`doi`),
    KEY `idx_01_publication_id` (`publication_id`),
    KEY `idx_01_paper_type` (`paper_type`),
    KEY `idx_01_publication_name_en` (`publication_name_en`(191)),
    KEY `idx_01_issn` (`issn`),
    KEY `idx_01_eissn` (`eissn`),
    KEY `idx_01_publication_year` (`publication_year`),
    KEY `idx_01_publication_date` (`publication_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='英文论文详情信息';
