CREATE TABLE `dwd_en_journal` (
  `id` bigint NOT NULL COMMENT '期刊、会议或预印本记录的唯一标识。',
  `issn` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊的国际标准连续出版物编号。',
  `zh_name` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊、顶会或预印本平台的中文名称。',
  `en_name` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊、顶会或预印本平台的英文名称。',
  `name_abbr` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊、会议或预印本名称的简称或缩写。',
  `publication_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '标识出版载体的类型，如期刊、会议或预印本等。journal，conference',
  `en_description` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '期刊、会议或预印本平台的英文简介或说明。',
  `establish_time` int DEFAULT NULL COMMENT '期刊首次创办或发行的时间。',
  `language` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '文献或期刊出版使用的语言类型。',
  `country` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊、会议或出版机构所属的国家或地区。',
  `eissn` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊电子版的国际标准连续出版物编号。',
  `annual_publication` int DEFAULT NULL COMMENT '期刊或会议每年发表文章的数量。',
  `review` tinyint DEFAULT NULL COMMENT '标识该期刊是否为综述类期刊。否=0，是=1，未知=2',
  `impact_factor` decimal(20,10) DEFAULT NULL COMMENT '期刊或会议的影响力评价指标。',
  `jcr_zone` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊在 JCR 等评价体系中的分区信息。Q1,Q2,Q3,Q4',
  `open_access` tinyint DEFAULT NULL COMMENT '标识期刊或论文是否为开放获取。否=0，是=1，未知=2',
  `review_period` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊从投稿到审稿完成的平均周期。',
  `scope` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊或会议所属的大类学科领域。',
  `sub_scope` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊或会议所属的细分学科主题。',
  `self_rate` decimal(20,10) DEFAULT NULL COMMENT '期刊文献中自我引用所占的比例。',
  `top` tinyint DEFAULT NULL COMMENT '标识期刊或会议是否为所在领域的顶级刊物。否=0，是=1',
  `warning` tinyint DEFAULT NULL COMMENT '标识期刊是否处于预警状态。否=0，是=1，未知=Null',
  `is_sci` tinyint DEFAULT NULL COMMENT '标识期刊是否被 SCI 收录。否=0，是=1，未知=Null',
  `publish_period` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊的出版频率或发行周期。',
  `jn_official` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '期刊官方网站地址。',
  `layout_cost` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊发表论文所需的版面费用。',
  `paper_nums` int DEFAULT NULL COMMENT '期刊、会议或平台已发表论文的数量。',
  `updated_time` datetime NOT NULL COMMENT '该条数据最近一次更新的时间。',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='深势-英文期刊详情信息';
