CREATE TABLE IF NOT EXISTS dwd_en_journal (
    `logical_id` VARCHAR(128) NOT NULL COMMENT '标题信息表逻辑主键',
    `paper_id` VARCHAR(64) NOT NULL COMMENT '文献记录的唯一主键标识。',
    `journal_id` BIGINT NOT NULL COMMENT '期刊、会议或预印本记录的唯一标识。',
    `publication_type` VARCHAR(255) COMMENT '标识出版载体的类型，如期刊、会议或预印本等。',
    `country` VARCHAR(255) COMMENT '期刊、会议或出版机构所属的国家或地区。',
    `journal_name_en` VARCHAR(1024) COMMENT '期刊、顶会或预印本平台的英文名称。',
    `journal_abbreviation` VARCHAR(255) COMMENT '期刊、会议或预印本名称的简称或缩写。',
    `journal_name_zh` VARCHAR(1024) COMMENT '期刊、顶会或预印本平台的中文名称。',
    `issn` VARCHAR(16) COMMENT '期刊的国际标准连续出版物编号。纸印出版 issn',
    `eissn` VARCHAR(16) COMMENT '期刊的国际标准连续出版物编号。在网发行 issn',
    `official_website` TEXT COMMENT '期刊官方网站地址。',
    `description` TEXT COMMENT '期刊、会议或预印本平台的英文简介或说明。',
    `founding_year` INT COMMENT '期刊首次创办或发行的时间。',
    `annual_publication_count` INT COMMENT '期刊或会议每年发表文章的数量。',
    `is_review_journal` TINYINT COMMENT '标识该期刊是否为综述类期刊。',
    `impact_factor` DOUBLE COMMENT '期刊或会议的影响力评价指标。',
    `quartile` VARCHAR(2) COMMENT '期刊在 JCR 等评价体系中的分区信息。',
    `review_period` VARCHAR(255) COMMENT '期刊从投稿到审稿完成的平均周期。',
    `self_citation_rate` DOUBLE COMMENT '期刊文献中自我引用所占的比例。',
    `top_flag` TINYINT COMMENT '标识期刊或会议是否为所在领域的顶级刊物。',
    `warning_flag` TINYINT COMMENT '标识期刊是否处于预警状态。',
    `sci_flag` TINYINT COMMENT '标识期刊是否被 SCI 收录。',
    `publication_cycle` VARCHAR(64) COMMENT '期刊的出版频率或发行周期。',
    `layout_cost` VARCHAR(15) COMMENT '期刊发表论文所需的版面费用。',
    `paper_count` INT COMMENT '期刊、会议或平台已发表论文的数量。',
    `data_source` VARCHAR(255) NOT NULL COMMENT '来源贴源库表名',
    `created_time` DATETIME NOT NULL COMMENT '数据在要素库中的创建时间。',
    `updated_time` DATETIME NOT NULL COMMENT '该条数据最近一次更新的时间。',
    KEY `idx_05_logical_id` (`logical_id`),
    KEY `idx_05_paper_id` (`paper_id`),
    KEY `idx_05_journal_id` (`journal_id`),
    KEY `idx_05_journal_name_en` (`journal_name_en`(191)),
    KEY `idx_05_journal_abbreviation` (`journal_abbreviation`),
    KEY `idx_05_journal_name_zh` (`journal_name_zh`(191)),
    KEY `idx_05_issn` (`issn`),
    KEY `idx_05_eissn` (`eissn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='英文期刊详情信息';
