CREATE TABLE `dwd_en_paper_info` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
  `eid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Scopus文献唯一标识',
  `doi` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '文献数字对象唯一标识符',
  `online_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '文献在线状态',
  `pui` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '出版商唯一标识',
  `sdfullavail` tinyint DEFAULT '0' COMMENT '全文可获取状态，0-不可获取，1-可获取',
  `issn` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '期刊国际标准刊号',
  `volume` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '期刊卷号',
  `issue` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '期刊期号',
  `first_page` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '文献起始页码',
  `last_page` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '文献结束页码',
  `sort_year` int DEFAULT NULL COMMENT '数据排序年份',
  `sort_yyyymm` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '数据排序年月',
  `pub_year` int DEFAULT NULL COMMENT '文献正式出版年份',
  `timestamp` datetime DEFAULT NULL COMMENT '文献数据更新时间戳',
  `orig_load_date` date DEFAULT NULL COMMENT '数据原始入库日期',
  `datesort` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '日期排序字符串',
  `indexeddate` datetime DEFAULT NULL COMMENT 'Scopus索引收录时间',
  `absavail` tinyint DEFAULT '0' COMMENT '摘要可获取状态，0-不可获取，1-可获取',
  `suppressdummy` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'no' COMMENT '是否隐藏虚拟数据',
  `srctype` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '文献来源类型，j-期刊',
  `subj_area` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '文献所属学科领域，多学科逗号分隔',
  `srctitle` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '期刊来源全称',
  `country` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '文献所属国家',
  `language` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '文献语种',
  `is_open_access` tinyint DEFAULT '0' COMMENT '是否开放获取，0-否，1-是',
  `oa_article_status` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '开放获取状态描述',
  `doctype` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '文献文档类型',
  `group_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '文献分组ID',
  `author_count` int DEFAULT '0' COMMENT '文献作者总数量',
  `author_list` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '作者完整信息列表，多作者分号分隔，含姓名、职称、作者ID等',
  `author_surname` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '第一作者姓氏',
  `author_initials` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '第一作者首字母缩写',
  `author_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '作者唯一标识',
  `title` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '文献中文/英文标题',
  `source_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '期刊来源唯一ID',
  `source_title_abbrev` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '期刊来源简称',
  `asjc_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'ASJC学科分类编码，多编码逗号分隔',
  `cited_by_count` int DEFAULT '0' COMMENT '被引用次数',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_eid` (`eid`)
) ENGINE=InnoDB AUTO_INCREMENT=10101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='爱思唯尔外文文献基础信息';
