CREATE TABLE `ods_en_journal` (
  `F_ID` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_PaperID` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_Title` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_title_alternative` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_abbrev_title` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_author` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_author_alternative` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_affiliation` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_affiliation_alternative` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_Abstract` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_Abstract_alternative` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_Keyword` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_Keyword_alternative` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_Language` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_Other_language` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_year` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_volume` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_issue` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_Paper_type` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_Classification` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_DOI` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_Start_page` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_End_page` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_page` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_Total_page_number` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_Journal` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_Journal_alternative` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_journal_abbrev` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_journal_id` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_ISSNp` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_ISSNe` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_DateReceived` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_DateSubmitted` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_DatePublish` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_DateRevision` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_Updatedtime` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `F_Content` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_Subject` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_column` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_column_alternative` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_AbstractUrl` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_FulltextUrl` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_PaperUrlContent` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_issue_url` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_journal_url` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `yn_free` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_Fund` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_Fundid` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_Fundaffiliation` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_refrences` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_publiser` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_batchid` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `F_article_id` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='万方外文期刊信息';
