CREATE TABLE `ods_zh_project` (
  `id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '主键',
  `project_number` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '项目编号',
  `title` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '项目名称',
  `project_source` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '项目来源',
  `funded_institution` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '依托单位',
  `project_level` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '项目级别',
  `funded_amount` decimal(12,2) DEFAULT NULL COMMENT '资助金额',
  `discipline` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '学科',
  `discipline_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '学科代码',
  `fund_category` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '基金类别',
  `funded_province` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '资助省份',
  `participating_institution` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '参与单位',
  `approval_year` date DEFAULT NULL COMMENT '批准年度',
  `approval_time` date DEFAULT NULL COMMENT '批准日期',
  `research_period` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '研究周期',
  `project_host` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '项目负责人',
  `participants` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '参与人员',
  `keywords` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '关键词',
  `abstract` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '项目摘要',
  `final_report_abstract` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '结题摘要',
  `project_page_url` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '项目详情页',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='深势-国内项目信息表';
