CREATE TABLE IF NOT EXISTS dwd_zh_project_output (
    `id` VARCHAR(64) NOT NULL COMMENT '项目记录的唯一主键标识。',
    `total_outputs` INT COMMENT '项目产生的成果总数量。',
    `journal_articles_count` INT COMMENT '项目产出的期刊论文数量。',
    `conference_papers_count` INT COMMENT '项目产出的会议论文数量。',
    `degree_papers_count` INT COMMENT '项目产出的学位论文数量。',
    `patents_count` INT COMMENT '项目产出的专利数量。',
    `books_count` INT COMMENT '项目产出的图书或专著数量。',
    `awards_count` INT COMMENT '项目获得的奖项数量。',
    `reports_count` INT COMMENT '项目产出的报告数量。',
    `other_outputs_count` INT COMMENT '项目产生的其他成果数量。',
    `output_journal_articles` JSON COMMENT '项目产出的期刊文章内容',
    `output_patents` JSON COMMENT '项目产出专利标题',
    `output_conference_papers` JSON COMMENT '项目产出会议论文标题',
    `output_degree_papers` JSON COMMENT '项目产出学位论文标题',
    `output_clinical_trials` JSON COMMENT '项目产出临床试验标题',
    `output_books` JSON COMMENT '项目产出图书专著标题',
    `output_awards` JSON COMMENT '项目产出奖项标题',
    `output_reports` JSON COMMENT '项目产出报告标题',
    `output_other` JSON COMMENT '项目其他产出标题',
    `updated_time` DATETIME NOT NULL COMMENT '该条数据最近一次更新的时间。',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='国内项目-产出信息';
