CREATE TABLE `dwd_zh_journal` (
  `id` bigint NOT NULL COMMENT '期刊记录的唯一标识。',
  `iscn` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊的国内统一刊号。',
  `issn` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊的国际标准连续出版物编号。',
  `zh_name` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊的中文名称。',
  `en_name` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊的英文名称。',
  `publication_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '出版物类别，例如期刊，会议等',
  `name_abbr` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊名称的简称或缩写。',
  `country` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊所属或出版所在的国家。',
  `zh_description` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '期刊的中文简介或说明。',
  `format` varchar(63) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊的版面开本规格。',
  `founding_time` int DEFAULT NULL COMMENT '期刊首次创办或发行的时间。',
  `language_classify` tinyint DEFAULT NULL COMMENT '期刊出版使用的语言类型。',
  `eissn` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊电子版的国际标准连续出版物编号。',
  `jn_official` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '期刊官方网站地址。',
  `postal_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊邮政发行使用的代号。',
  `chief_editor` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊当前或记录中的主编信息。',
  `organizer` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '负责主办该期刊的单位名称。',
  `publisher_place` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊出版发行的地点。',
  `publication_cycle` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊的出版频率或发行周期。',
  `award` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '期刊获得的奖项或荣誉信息。',
  `cite_nums` int DEFAULT NULL COMMENT '期刊或文献的累计被引用次数。',
  `paper_nums` int DEFAULT NULL COMMENT '期刊已发表论文的数量。',
  `review` tinyint DEFAULT NULL COMMENT '标识该期刊是否为综述类期刊。',
  `annual_publication` int DEFAULT NULL COMMENT '期刊每年发表文章的数量。',
  `impact_factor` decimal(20,10) DEFAULT NULL COMMENT '期刊的影响因子指标。',
  `open_access` tinyint DEFAULT NULL COMMENT '标识期刊或论文是否为开放获取。',
  `scope` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊所属的大类学科领域。',
  `scope_zone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '期刊所属的细分学科领域。',
  `warning` tinyint DEFAULT NULL COMMENT '标识期刊是否处于预警状态。',
  `is_sci` tinyint DEFAULT NULL COMMENT '标识期刊是否被 SCI 收录。',
  `sub_quartile` tinyint DEFAULT NULL COMMENT '期刊在相关评价体系中的分区信息。',
  `classify_list` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '文献或期刊对应的学科分类编号。',
  `updated_time` datetime NOT NULL COMMENT '该条数据最近一次更新的时间。',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='深势-中文期刊详情信息';
