CREATE TABLE `ods_zh_journal` (
  `lngid` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `media_c` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `media_e` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `gch` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `gch5` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `years` int DEFAULT NULL,
  `vol` int DEFAULT NULL,
  `num` int DEFAULT NULL,
  `title_c` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `title_e` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `keyword_c` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `keyword_e` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `remark_c` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `remark_e` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `firstclass` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `class` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `beginpage` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `endpage` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `jumppage` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `pagecount` int DEFAULT NULL,
  `firstwriter` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `showwriter` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `firstorgan` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `showorgan` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `showwriter_e` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `showorgan_e` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `author_e` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `publishdate` int DEFAULT NULL,
  `doi` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `intpdf` int DEFAULT NULL,
  `pdfsize` int DEFAULT NULL,
  `range` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `language` int DEFAULT NULL,
  `type` int DEFAULT NULL,
  `issn` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `cnno` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `classtypes` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `showclasstypes` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `subject_edu` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `corr_author` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `fulltextaddress` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='维普中文报告信息';
