CREATE TABLE IF NOT EXISTS dwd_zh_journal (
    `logical_id` VARCHAR(128) NOT NULL COMMENT '标题信息表逻辑主键',
    `paper_id` VARCHAR(64) NOT NULL COMMENT '文献记录的唯一主键标识。',
    `journal_id` BIGINT NOT NULL COMMENT '期刊记录的唯一标识。',
    `publication_type` VARCHAR(255) COMMENT '出版物类别，例如期刊，会议等',
    `country` VARCHAR(255) COMMENT '期刊所属或出版所在的国家。',
    `journal_name_zh` VARCHAR(1024) COMMENT '期刊的中文名称。',
    `journal_abbreviation` VARCHAR(255) COMMENT '期刊名称的简称或缩写。',
    `journal_name_en` VARCHAR(1024) COMMENT '期刊的英文名称。',
    `iscn` VARCHAR(16) COMMENT '期刊的国内统一刊号。',
    `issn` VARCHAR(16) COMMENT '期刊的国际标准连续出版物编号。',
    `eissn` VARCHAR(16) COMMENT '期刊电子版的国际标准连续出版物编号。',
    `founding_year` INT COMMENT '期刊首次创办或发行的时间。',
    `official_website` TEXT COMMENT '期刊官方网站地址。',
    `description` TEXT COMMENT '期刊的中文简介或说明。',
    `format` TINYTEXT COMMENT '期刊的版面开本规格。',
    `postal_code` VARCHAR(32) COMMENT '期刊邮政发行使用的代号。',
    `chief_editor` VARCHAR(128) COMMENT '期刊当前或记录中的主编信息。',
    `organizer` VARCHAR(1024) COMMENT '负责主办该期刊的单位名称。',
    `publication_place` VARCHAR(64) COMMENT '期刊出版发行的地点。',
    `awards` TEXT COMMENT '期刊获得的奖项或荣誉信息。',
    `citation_count` INT COMMENT '期刊或文献的累计被引用次数。',
    `annual_publication_count` INT COMMENT '期刊每年发表文章的数量。',
    `is_review_journal` TINYINT COMMENT '标识该期刊是否为综述类期刊。',
    `impact_factor` DOUBLE COMMENT '期刊的影响因子指标。',
    `quartile` TINYINT COMMENT '期刊在相关评价体系中的分区信息。Subject Quartile in Category分区',
    `classification_code` TEXT COMMENT '文献或期刊对应的学科分类编号。',
    `warning_flag` TINYINT COMMENT '标识期刊是否处于预警状态。',
    `sci_flag` TINYINT COMMENT '标识期刊是否被 SCI 收录。',
    `publication_cycle` VARCHAR(64) COMMENT '期刊的出版频率或发行周期。',
    `paper_count` INT COMMENT '期刊已发表论文的数量。',
    `data_source` VARCHAR(255) NOT NULL COMMENT '来源贴源库表名',
    `created_time` DATETIME NOT NULL COMMENT '数据在要素库中的创建时间。',
    `updated_time` DATETIME NOT NULL COMMENT '该条数据最近一次更新的时间。',
    KEY `idx_05_logical_id` (`logical_id`),
    KEY `idx_05_paper_id` (`paper_id`),
    KEY `idx_05_journal_id` (`journal_id`),
    KEY `idx_05_journal_name_zh` (`journal_name_zh`(191)),
    KEY `idx_05_journal_abbreviation` (`journal_abbreviation`),
    KEY `idx_05_journal_name_en` (`journal_name_en`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='中文期刊详情信息';
