CREATE TABLE IF NOT EXISTS dwd_patent (
    patent_id VARCHAR(64) NOT NULL COMMENT '专利记录唯一标识，与 DOCDB 兼容',
    publication_number VARCHAR(64) NOT NULL COMMENT '专利公布号',
    application_kind VARCHAR(2) COMMENT '专利申请类型代码',
    country_code VARCHAR(2) COMMENT '国家、地区或组织代码',
    country VARCHAR(20) COMMENT '专利所属或发布的国家名称',
    publication_reference JSON COMMENT '发布文献种类代码、发布日期、年份和年月',
    application_reference JSON COMMENT '申请号、受理局代码、申请日期、年份和年月',
    pct_or_regional_filing_data JSON COMMENT 'PCT 申请号和申请日期',
    pct_or_regional_publishing_data JSON COMMENT 'PCT 公布号和公布日期',
    priority_filings JSON COMMENT '优先权信息对象数组',
    applicants JSON COMMENT '原始申请人对象数组',
    assignees JSON COMMENT '当前申请人或专利权人对象数组',
    inventors JSON COMMENT '发明人对象数组',
    first_applicant_name VARCHAR(255) COMMENT '第一原始申请人',
    first_current_assignee_name VARCHAR(255) COMMENT '第一当前申请人或专利权人',
    first_inventor_name VARCHAR(255) COMMENT '第一发明人',
    classification_ipcr JSON COMMENT 'IPCR/IPC 主分类号和附加分类号',
    classification_cpc JSON COMMENT 'CPC 主分类号和附加分类号',
    keywords TEXT COMMENT '描述专利主题内容的关键词',
    claims_localized TEXT COMMENT '专利权利要求书的文本内容',
    description_localized TEXT COMMENT '专利说明书的正文内容',
    figures TEXT COMMENT '专利附图或图示相关信息',
    `language` VARCHAR(16) COMMENT '专利原始文本使用的语言',
    granted_number VARCHAR(64) COMMENT '专利授权编号',
    spif_application_number VARCHAR(64) COMMENT 'SPIF 标准申请号',
    spif_publication_number VARCHAR(64) COMMENT 'SPIF 标准公布号',
    prior_art_year VARCHAR(4) COMMENT '相关现有技术对应的年份',
    prior_art_date VARCHAR(10) COMMENT '相关现有技术对应的日期',
    relevants TEXT COMMENT '相关专利信息',
    db_source VARCHAR(64) NOT NULL COMMENT '数据来源贴源库',
    create_time DATETIME NOT NULL COMMENT '记录创建时间',
    update_time DATETIME NOT NULL COMMENT '记录最近更新时间',
    citation_nums BIGINT COMMENT '引用专利数量',
    patent_citations JSON COMMENT '引用专利对象数组',
    cited_by_nums BIGINT COMMENT '被引专利数量',
    cited_by JSON COMMENT '被引专利对象数组',
    non_patent_citations_nums BIGINT COMMENT '非专利文献引用数量',
    non_patent_citations JSON COMMENT '非专利文献引用对象数组',
    dates_of_public_availability JSON COMMENT '授权日期、年份和年月',
    `status` VARCHAR(10) COMMENT '专利当前法律状态',
    anticipated_expiration DATE COMMENT '预计到期日',
    expiration_year VARCHAR(10) COMMENT '预计或实际到期年份',
    family_citations TEXT COMMENT '家族内引用信息',
    cited_by_family TEXT COMMENT '家族内被引用信息',
    other_versions TEXT COMMENT '其他公开、公告或授权版本',
    worldwides TEXT COMMENT '全球同族专利信息',
    simple_family JSON COMMENT '简单同族成员文献号',
    PRIMARY KEY (patent_id),
    KEY idx_dwd_patent_publication_number (publication_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='专利信息表';

