CREATE TABLE `ods_patent` (
  `id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '专利公布号(与DOCDB兼容)',
  `publication_number` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '专利公布号',
  `pct_publication_number` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'pct公开号',
  `application_number` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '专利申请号',
  `country_code` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '国家代码',
  `kind_code` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '种类代码',
  `application_kind` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应用程序类型',
  `application_number_formatted` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '格式化的申请号',
  `pct_number` varchar(17) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'PCT编号',
  `family_id` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '家庭ID',
  `spif_publication_number` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SPIF标准发布编号',
  `spif_application_number` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SPIF标准申请号',
  `title_localized` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '标题',
  `abstract_localized` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '摘要',
  `claims_localized` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '权利要求',
  `claims_localized_html` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '权利要求html',
  `description_localized` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '说明书',
  `description_localized_html` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '说明书html',
  `publication_year` int DEFAULT NULL COMMENT '发布年份',
  `filing_year` int DEFAULT NULL COMMENT '申请年份',
  `grant_year` int DEFAULT NULL COMMENT '授予年份',
  `priority_year` int DEFAULT NULL COMMENT '优先权年',
  `expiration_year` int DEFAULT NULL COMMENT '失效年',
  `citation_nums` int DEFAULT NULL COMMENT '专利引用数量',
  `cited_by_nums` int DEFAULT NULL COMMENT '专利施引数量',
  `publication_date` date DEFAULT NULL COMMENT '发布日期',
  `filing_date` date DEFAULT NULL COMMENT '申请日期',
  `grant_date` date DEFAULT NULL COMMENT '授予日期',
  `priority_date` date DEFAULT NULL COMMENT '优先权日',
  `priority_claim` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '本出版物',
  `inventor` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '发明人',
  `inventor_harmonized` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '发明者信息',
  `assignee` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '受让人/申请人',
  `current_assignee` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '当前受让人/申请人',
  `assignee_harmonized` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '受让人/申请人信息',
  `examiner` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '审查员信息',
  `uspc` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '美国专利',
  `ipc` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '国际专利分类',
  `cpc` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '合作专利分类',
  `fi` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'FI分类',
  `fterm` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'fterm分类',
  `locarno` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Locarno分类',
  `citation` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '出版物引用',
  `parent` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '父申请',
  `child` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '子申请',
  `entity_status` varchar(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '美国专利商标局实体状态',
  `art_unit` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '美国专利商标局艺术单位',
  `status` varchar(55) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '专利状态',
  `figures` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '专利图',
  `pdf_url` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '专利文件链接',
  `patent_citations` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '专利引用',
  `family_citations` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '家族内引用',
  `cited_by` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '被引用',
  `cited_by_family` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '家庭内被引用',
  `events` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '事件',
  `non_patent_citations` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '非专利引用',
  `legal_events` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '法律事件',
  `anticipated_expiration` date DEFAULT NULL COMMENT '预计到期日',
  `language` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '原文语言',
  `relevants` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '相关专利',
  `priority_filings` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '优先权信息',
  `precis_graph` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '摘要图AI生成OSS链接',
  `targets` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '靶点',
  `keywords` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '关键词',
  `concepts` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '概念',
  `definitions` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '定义',
  `worldwides` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '全球专利',
  `docdb_family` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '家族专利',
  `prior_art_date` date DEFAULT NULL COMMENT 'Prior art date',
  `prior_art_year` int DEFAULT NULL COMMENT 'Prior art year',
  `country` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '国家',
  `other_versions` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '其他版本',
  `external_links` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '外部链接',
  `landscapes` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '技术领域分类',
  `dwpi_basic` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'DWPI基本专利，指第一个输入到DWPI数据库的同族专利成员',
  `dwpi_family` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'DWPI同族公开号',
  `main_family` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '同族专利公开号',
  `complete_family` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '拓展同族公开号',
  `legal_status` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '法律状态',
  `transferor` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '转让人',
  `transfer_count` int DEFAULT NULL COMMENT '转让次数',
  `transfer_price` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '转让价格',
  `transfer_record` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '转让时间序列',
  `license_type` int DEFAULT NULL COMMENT '许可类型，如独占许可、排他许可、普通许可等许可方式',
  `license_country` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '许可地国家，专利许可在哪些国家或地区有效',
  `license_price` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '许可费用',
  `examination_detail` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '审察详细信息',
  `technical_abstract` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '技术摘要',
  `page_count` int DEFAULT NULL COMMENT '文献页数',
  `subject_classification` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '学科分类',
  `dwpi_classification` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'DWPI分类',
  `dwpi_title` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'DWPI标题',
  `dwpi_priority_number` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'DWPI优先权号',
  `dwpi_priority_country` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'DWPI优先权国别',
  `dwpi_assignee` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'DWPI专利权人',
  `dwpi_inventor` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'DWPI发明人',
  `inpadoc_family_id` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'INPADOC同族编号',
  `independent_claims_localized` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '独立权利要求',
  `independent_claims_localized_html` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '独立权利要求html',
  `problem_sum` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '技术问题',
  `method_sum` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '技术手段',
  `benefit_sum` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '技术功效',
  `current_assignee_harmonized` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '当前受让人/申请人信息',
  `current_inventor` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '当前发明人',
  `current_inventor_harmonized` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '当前发明者信息',
  `agent` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '代理人',
  `current_agent` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '当前代理人',
  `agency` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '代理机构',
  `current_agency` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '当前代理机构',
  `assistant_examiner` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '助理审查员信息',
  `priority_country` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '优先权国家/地区',
  `epds` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'EP指定国家/地区',
  `business_information` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '工商信息',
  `first_publication_date` date DEFAULT NULL COMMENT '首次公开日',
  `examine_date` date DEFAULT NULL COMMENT '实质审查生效日',
  `pct_entry_date` date DEFAULT NULL COMMENT 'PCT进入国家阶段日',
  `legal_status_date` date DEFAULT NULL COMMENT '法律状态更新日',
  `earliest_priority_date` date DEFAULT NULL COMMENT '最早优先权日',
  `gbc` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '国民经济行业分类号',
  `adc` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '应用领域分类',
  `ttc` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '技术主题分类',
  `seic` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '战略新兴产业分类',
  `cite_category` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '引用类别',
  `epds_count` int DEFAULT NULL COMMENT 'EP指定国家/地区数量',
  `up_status` int DEFAULT NULL COMMENT '欧洲统一法院状态',
  `epds_legal_status` int DEFAULT NULL COMMENT 'EP指定国家/地区法律状态',
  `patent_value` int DEFAULT NULL COMMENT '专利价值(美元)',
  `gov` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '政府利益',
  `examine_period` int DEFAULT NULL COMMENT '审查时长',
  `sep` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '标准专利',
  `award` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '奖励',
  `sub_case` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '分案',
  `priority_country_count` int DEFAULT NULL COMMENT '优先权国家/地区个数',
  `case_number` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '案件号',
  `court` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '审查法院',
  `judge` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '审判员',
  `chief_judge` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '审判长',
  `plaintiff` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '原告',
  `defendant` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '被告',
  `case_filing_date` date DEFAULT NULL COMMENT '立案日期',
  `verdict_date` date DEFAULT NULL COMMENT '裁判日期',
  `hearing_date` date DEFAULT NULL COMMENT '听证日期',
  `trial_grade` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '审理程序',
  `case` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '案件',
  `case_close_date` date DEFAULT NULL COMMENT '结案日期',
  `outcome` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '案件结果',
  `litigation_count` int DEFAULT NULL COMMENT '诉讼次数',
  `case_doc_type` int DEFAULT NULL COMMENT '文书类型',
  `court_grade` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '法院级别',
  `verdict` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '判决结果',
  `party` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '当事人',
  `amount_plaintiff` int DEFAULT NULL COMMENT '申请赔偿总额',
  `damages_amount` int DEFAULT NULL COMMENT '判赔总额',
  `case_filing_year` int DEFAULT NULL COMMENT '立案年份',
  `litigation_product` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '涉及产品',
  `licensor` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '许可人',
  `licensee` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '被许可人',
  `license_number` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '许可合同备案号',
  `exclusivity` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '许可排他性',
  `license_effective_date` date DEFAULT NULL COMMENT '许可生效日',
  `license_count` int DEFAULT NULL COMMENT '许可次数',
  `transfer` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '权利转移',
  `review_invalid_applicant` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '复审/无效请求人',
  `review_invalid_decision_number` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '决定号',
  `review_invalid_commission_number` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '委内编号',
  `review_invalid_decision_date` date DEFAULT NULL COMMENT '决定/发文日',
  `review_invalid_decision_type` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '决定类型',
  `review_invalid_decision` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '决定',
  `review_invalid_decision_point` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '决定要点',
  `review_invalid_decision_case_mainpoint` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '案由',
  `review_invalid_legal_basis` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '法律依据',
  `review_invalid_fulltext` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '复审/无效全文',
  `invalid_count` int DEFAULT NULL COMMENT '无效次数',
  `pledgor` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '质押人',
  `pledgee` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '质权人',
  `pledgeno` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '质押登记号',
  `pledge` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '质押信息',
  `summarize` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '总结',
  `spare_zero` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '备用0',
  `spare_one` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '备用1',
  `spare_two` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '备用2',
  `spare_three` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '备用3',
  `spare_four` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '备用4',
  `spare_five` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '备用5',
  `spare_six` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '备用6',
  `spare_seven` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '备用7',
  `spare_eight` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '备用8',
  `spare_nine` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '备用9',
  `spare_ten` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '备用10',
  `state` tinyint DEFAULT '1' COMMENT '逻辑删除(1:存在，0:不存在)',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='深势-专利信息表';
