CREATE TABLE `ods_patent_weipu` (
  `lngid` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `media_c` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `years` int DEFAULT NULL,
  `title_c` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `title_e` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `keyword_c` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `keyword_e` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `remark_c` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `remark_e` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `class` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `firstclass` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `beginpage` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `endpage` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `jumppage` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `pagecount` int DEFAULT NULL,
  `showwriter` varchar(512) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `author_e` varchar(512) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `showorgan` varchar(512) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `intpdf` int DEFAULT NULL,
  `country` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `language` int DEFAULT NULL,
  `type` int DEFAULT NULL,
  `classtypes` varchar(512) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `showclasstypes` varchar(512) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `fulltextaddress` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `zlmaintype` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `zlapplicantaddr` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `zlprovincecode` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `zlapplicationnum` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `zlapplicationdata` int DEFAULT NULL,
  `zlopendata` int DEFAULT NULL,
  `zlpriority` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `zlprioritynumber` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `zlmainclassnum` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `zlclassnum` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `zlinternationalpub` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `zlinternationalapp` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `zlcomeindata` int DEFAULT NULL,
  `zlsovereignty` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `zlagents` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `zlagency` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `zllegalstatus` varchar(512) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `zlthesissize` int DEFAULT NULL,
  `zlaccdate` int DEFAULT NULL,
  `zlpatentstate` varchar(512) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='维普专利信息';
