-- 回滚脚本：N/C 删主键；S 删主键+代理列
ALTER TABLE `dwd_bid_base_out` DROP PRIMARY KEY;
ALTER TABLE `dwd_bid_purchase_agency_out` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_bid_target_item_out` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_bid_win_candidate_out` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_en_author` DROP PRIMARY KEY;
ALTER TABLE `dwd_en_journal` DROP PRIMARY KEY;
ALTER TABLE `dwd_en_paper` DROP PRIMARY KEY;
ALTER TABLE `dwd_en_paper_citation` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_en_paper_classification` DROP PRIMARY KEY;
ALTER TABLE `dwd_en_paper_reference` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_en_paper_related` DROP PRIMARY KEY;
ALTER TABLE `dwd_en_project` DROP PRIMARY KEY;
ALTER TABLE `dwd_en_project_output` DROP PRIMARY KEY;
ALTER TABLE `dwd_en_report` DROP PRIMARY KEY;
ALTER TABLE `dwd_forg_act_contro_info` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_forg_base_info` DROP PRIMARY KEY;
ALTER TABLE `dwd_forg_beneficiary_info` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_forg_executive_info` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_forg_product_info` DROP PRIMARY KEY;
ALTER TABLE `dwd_forg_shareholder_info` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_forg_stock_fin_info` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_forg_subsidiary_info` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_industry_chain_info` DROP PRIMARY KEY;
ALTER TABLE `dwd_industry_chain_news_info` DROP PRIMARY KEY;
ALTER TABLE `dwd_org_annual_financial_info` DROP PRIMARY KEY;
ALTER TABLE `dwd_org_bankruptcy_public_cases` DROP PRIMARY KEY;
ALTER TABLE `dwd_org_bankruptcy_public_cases_list` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_base_info` DROP PRIMARY KEY;
ALTER TABLE `dwd_org_changerecord_info` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_company_abnormal` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_company_illegal` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_company_punish` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_executive_info` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_financing_info` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_heis_info` DROP PRIMARY KEY;
ALTER TABLE `dwd_org_important_news_info` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_industry_chain_dtl` DROP PRIMARY KEY;
ALTER TABLE `dwd_org_industry_chain_prod_dtl` DROP PRIMARY KEY;
ALTER TABLE `dwd_org_invest_info` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_merger_acquisition_info` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_opt_judicial_case` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_org_product_info` DROP PRIMARY KEY;
ALTER TABLE `dwd_org_recruit_info` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_risk_shixin` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_risk_tax_punish` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_risk_zhixing` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_shareholder_info` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_stock_base` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_org_stock_finance_info` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_research_institute_base_info` DROP PRIMARY KEY;
ALTER TABLE `dwd_scholar` DROP PRIMARY KEY;
ALTER TABLE `dwd_scholar_coauthor` DROP PRIMARY KEY;
ALTER TABLE `dwd_scholar_paper_relation` DROP PRIMARY KEY;
ALTER TABLE `dwd_scholar_papers` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_scholar_research_direction` DROP PRIMARY KEY;
ALTER TABLE `dwd_scholar_talent_flag` DROP PRIMARY KEY;
ALTER TABLE `dwd_special_aomen_company` DROP PRIMARY KEY;
ALTER TABLE `dwd_special_hongkong_company` DROP PRIMARY KEY;
ALTER TABLE `dwd_special_taiwan_company` DROP PRIMARY KEY;
ALTER TABLE `dwd_zck_intl_policy` DROP PRIMARY KEY;
ALTER TABLE `dwd_zh_author` DROP PRIMARY KEY;
ALTER TABLE `dwd_zh_journal` DROP PRIMARY KEY;
ALTER TABLE `dwd_zh_paper` DROP PRIMARY KEY;
ALTER TABLE `dwd_zh_paper_citation` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_zh_paper_classification` DROP PRIMARY KEY;
ALTER TABLE `dwd_zh_paper_reference` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_zh_paper_related` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dwd_zh_project` DROP PRIMARY KEY;
ALTER TABLE `dwd_zh_project_output` DROP PRIMARY KEY;
ALTER TABLE `dwd_zh_report` DROP PRIMARY KEY;
ALTER TABLE `dwd_zh_report_paper` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `dws_zck_policy` DROP PRIMARY KEY;
ALTER TABLE `ods_en_journal` DROP PRIMARY KEY;
ALTER TABLE `ods_en_report` DROP PRIMARY KEY, DROP COLUMN `row_pk`;
ALTER TABLE `ods_zh_journal` DROP PRIMARY KEY;
ALTER TABLE `dwd_en_paper_abstract` DROP PRIMARY KEY;
ALTER TABLE `dwd_en_paper_funding` DROP PRIMARY KEY;
ALTER TABLE `dwd_en_paper_title` DROP PRIMARY KEY;
ALTER TABLE `dwd_en_report_author` DROP PRIMARY KEY;
ALTER TABLE `dwd_en_report_org` DROP PRIMARY KEY;
ALTER TABLE `dwd_zh_paper_abstract` DROP PRIMARY KEY;
ALTER TABLE `dwd_zh_paper_title` DROP PRIMARY KEY;
ALTER TABLE `dwd_zh_report_org` DROP PRIMARY KEY;
ALTER TABLE `dwd_zh_report_project` DROP PRIMARY KEY;
ALTER TABLE `dwd_zh_report_scholar` DROP PRIMARY KEY;
ALTER TABLE `ods_en_author` DROP PRIMARY KEY;
ALTER TABLE `ods_en_paper` DROP PRIMARY KEY;
ALTER TABLE `ods_en_paper_abstract` DROP PRIMARY KEY;
ALTER TABLE `ods_en_paper_citation` DROP PRIMARY KEY;
ALTER TABLE `ods_en_paper_classification` DROP PRIMARY KEY;
ALTER TABLE `ods_en_paper_funding` DROP PRIMARY KEY;
ALTER TABLE `ods_en_paper_reference` DROP PRIMARY KEY;
ALTER TABLE `ods_en_paper_title` DROP PRIMARY KEY;
ALTER TABLE `ods_zh_paper_abstract` DROP PRIMARY KEY;
ALTER TABLE `ods_zh_paper_author` DROP PRIMARY KEY;
ALTER TABLE `ods_zh_paper_classification` DROP PRIMARY KEY;
ALTER TABLE `ods_zh_paper_reference` DROP PRIMARY KEY;
ALTER TABLE `ods_zh_paper_title` DROP PRIMARY KEY;
