CREATE TABLE project_foreign (
    -- 1. 项目基本信息
    project_id VARCHAR(64) PRIMARY KEY COMMENT '项目编号',
    title VARCHAR(500) COMMENT '项目名称',
    project_source VARCHAR(255) COMMENT '项目来源',
    funded_institution VARCHAR(255) COMMENT '项目受资助机构',
    project_level VARCHAR(255) COMMENT '项目级别',
    funded_amount DECIMAL(18,2) COMMENT '受资助金额',
    discipline VARCHAR(255) COMMENT '学科',
    discipline_code VARCHAR(64) COMMENT '学科代码',
    fund_category VARCHAR(255) COMMENT '基金类别',
    funded_province VARCHAR(255) COMMENT '项目受资助省',
    participating_institution TEXT COMMENT '参与机构',
    approval_year INT COMMENT '立项年度',
    approval_time DATE COMMENT '立项时间',
    research_period VARCHAR(255) COMMENT '研究期限',
    project_host VARCHAR(255) COMMENT '项目主持人',
    participants TEXT COMMENT '参与者',
    keywords TEXT COMMENT '关键词',
    abstract TEXT COMMENT '项目标书摘要',
    final_report TEXT COMMENT '项目结题报告',
    project_page_url TEXT COMMENT '项目页面 URL',
    participant_id VARCHAR(64) COMMENT '参与人ID；英文名为自定义，图中仅提供中文字段描述',
    project_domain VARCHAR(255) COMMENT '项目领域',

    -- 2. 关联成果信息
    total_outputs INT COMMENT '项目总产出数量',
    journal_articles_count INT COMMENT '期刊文章数量',
    conference_papers_count INT COMMENT '会议论文数量',
    degree_papers_count INT COMMENT '学位论文数量',
    patents_count INT COMMENT '专利数量',
    clinical_trials_count INT COMMENT '临床试验数量',
    books_count INT COMMENT '图书专著数量',
    products_count INT COMMENT '产品数量',
    awards_count INT COMMENT '奖项数量',
    reports_count INT COMMENT '报告数量',
    other_outputs_count INT COMMENT '其他产出数量',
    output_article_title VARCHAR(500) COMMENT '产出文章标题',
    output_article_authors TEXT COMMENT '产出文章作者',
    output_article_journal VARCHAR(255) COMMENT '产出文章期刊',
    output_article_year INT COMMENT '产出文章发表年份',
    output_article_issue VARCHAR(64) COMMENT '产出文章期数',
    output_article_keywords TEXT COMMENT '产出文章关键词',
    output_article_abstract TEXT COMMENT '产出文章摘要',
    output_article_source_url TEXT COMMENT '产出文章来源 URL',

    -- 3. 其它字段需求
    paper_ids JSON COMMENT '项目产出论文ID（请使用ID数组存储，以应对多篇产出）',
    patent_ids JSON COMMENT '项目产出专利ID（请使用ID数组存储，以应对多篇产出）'
);