CREATE TABLE IF NOT EXISTS dwd_org_reg_info (
    `org_id` VARCHAR(255) NOT NULL COMMENT '机构身份唯一id，用于关联其它表。',
    `name_cn` VARCHAR(255) NOT NULL COMMENT '机构名称',
    `external_id` VARCHAR(255) COMMENT '统一社会信用代码',
    `province` VARCHAR(255) COMMENT '所在省份',
    `city` VARCHAR(255) COMMENT '所在城市',
    `address` TEXT COMMENT '公司地址',
    `addr_lng` VARCHAR(255) COMMENT '地址对应经度',
    `addr_lat` VARCHAR(255) COMMENT '地址对应维度',
    `postal_code` VARCHAR(255) COMMENT '邮政编码',
    `phone` VARCHAR(255) COMMENT '联系电话',
    `email` TEXT COMMENT '电子邮箱',
    `lerep` VARCHAR(255) COMMENT '法人名字',
    `org_type` VARCHAR(255) COMMENT '机构类型',
    `org_size` VARCHAR(255) COMMENT '企业规模',
    `registration_org` VARCHAR(255) COMMENT '登记机关',
    `incorporation_year` BIGINT COMMENT '成立年份',
    `incorporation_date` DATE COMMENT '成立日期',
    `start_date` VARCHAR(255) COMMENT '经营期限自',
    `end_date` VARCHAR(255) COMMENT '经营期限至',
    `listing_status` VARCHAR(255) COMMENT '上市状态',
    `listing_date` DATE COMMENT '上市日期',
    `registered_capital_value` DECIMAL(20,2) COMMENT '注册资本(本币元)',
    `capital_currency_code` VARCHAR(255) COMMENT '资本货币代码',
    `data_source` VARCHAR(255) NOT NULL COMMENT '数据来源',
    `created_time` DATETIME NOT NULL COMMENT '创建时间',
    `updated_time` DATETIME NOT NULL COMMENT '更新时间',
    KEY `idx_dwd_org_reg_info_org_id` (`org_id`),
    KEY `idx_dwd_org_reg_info_external_id` (`external_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='机构基本信息';
