CREATE TABLE IF NOT EXISTS dwd_org_annual_financial_info (
    `org_id` VARCHAR(255) NOT NULL COMMENT '机构身份唯一id，用于关联其它表。',
    `name_cn` VARCHAR(255) NOT NULL COMMENT '机构名称',
    `external_id` VARCHAR(255) COMMENT '统一社会信用代码',
    `year` BIGINT NOT NULL COMMENT '年报年度',
    `total_assets` VARCHAR(255) COMMENT '资产总额',
    `total_liabilities` VARCHAR(255) COMMENT '负债总额',
    `operating_revenue` VARCHAR(255) COMMENT '营业收入',
    `main_business_revenue` VARCHAR(255) COMMENT '主营业务收入',
    `total_profit` VARCHAR(255) COMMENT '利润总额',
    `pure_profit` VARCHAR(255) COMMENT '净利润',
    `total_tax_paid` VARCHAR(255) COMMENT '纳税总额',
    `owners_equity` VARCHAR(255) COMMENT '所有者权益合计',
    `employees_number` VARCHAR(255) COMMENT '从业人数',
    `data_source` VARCHAR(255) NOT NULL COMMENT '数据来源',
    `created_time` DATETIME NOT NULL COMMENT '创建时间',
    `updated_time` DATETIME NOT NULL COMMENT '更新时间',
    KEY `idx_dwd_org_annual_financial_info_org_id` (`org_id`),
    KEY `idx_dwd_org_annual_financial_info_external_id` (`external_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='年报财务信息';
