CREATE TABLE IF NOT EXISTS dwd_org_hels_info (
    `org_id` VARCHAR(255) NOT NULL COMMENT '机构身份唯一id，用于关联其它表。',
    `name_cn` VARCHAR(255) NOT NULL COMMENT '机构名称',
    `external_id` VARCHAR(255) COMMENT '统一社会信用代码',
    `org_name` VARCHAR(255) NOT NULL COMMENT '高校/科研机构名称(中文)',
    `org_name_en` VARCHAR(255) COMMENT '高校/科研机构名称(英文)',
    `org_desc` TEXT COMMENT '高校/科研机构描述',
    `est_year` DATE COMMENT '建立时间',
    `address` TEXT COMMENT '地址(国家、区域、城市)',
    `addr_lng` VARCHAR(255) COMMENT '地址对应经度',
    `addr_lat` VARCHAR(255) COMMENT '地址对应维度',
    `province` VARCHAR(255) COMMENT '地址所在省',
    `city` VARCHAR(255) COMMENT '地址所在市',
    `univ_type` VARCHAR(255) COMMENT '高校类型',
    `web_link` TEXT COMMENT '官方网址',
    `postal_code` VARCHAR(255) COMMENT '邮政编码',
    `email` TEXT COMMENT '电子邮箱',
    `contact_number` VARCHAR(255) COMMENT '联系电话',
    `fax_number` VARCHAR(255) COMMENT '传真号码',
    `data_source` VARCHAR(255) NOT NULL COMMENT '数据来源',
    `created_time` DATETIME NOT NULL COMMENT '创建时间',
    `updated_time` DATETIME NOT NULL COMMENT '更新时间',
    KEY `idx_dwd_org_hels_info_org_id` (`org_id`),
    KEY `idx_dwd_org_hels_info_external_id` (`external_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='高校/科研机构信息';
