CREATE TABLE IF NOT EXISTS dwd_org_stock_finance_info (
    `org_id` VARCHAR(255) NOT NULL COMMENT '机构身份唯一id，用于关联其它表。',
    `name_cn` VARCHAR(255) NOT NULL COMMENT '机构名称',
    `stock_code` VARCHAR(255) NOT NULL COMMENT '股票代码',
    `external_id` VARCHAR(255) COMMENT '统一社会信用代码',
    `occur_period` VARCHAR(255) NOT NULL COMMENT '数据期',
    `total_assets` DECIMAL(20,2) COMMENT '资产总额(元)',
    `fixed_assets` DECIMAL(20,2) COMMENT '固定资产总额(元)',
    `total_liabilities` DECIMAL(20,2) COMMENT '负债总额(元)',
    `operating_revenue` DECIMAL(20,2) COMMENT '营业收入(元)',
    `main_business_revenue` DECIMAL(20,2) COMMENT '主营业务收入(元)',
    `total_profit` DECIMAL(20,2) COMMENT '利润总额(元)',
    `pure_profit` DECIMAL(20,2) COMMENT '净利润(元)',
    `total_tax_paid` DECIMAL(20,2) COMMENT '纳税总额(元)',
    `oper_cash_flow` DECIMAL(20,2) COMMENT '经营活动现金流(元)',
    `owners_equity` DECIMAL(20,2) COMMENT '所有者权益合计(元)',
    `employees_number` BIGINT COMMENT '从业人数',
    `research_development_amount` DECIMAL(20,2) COMMENT '研发投入金额(元)',
    `data_source` VARCHAR(255) NOT NULL COMMENT '数据来源',
    `created_time` DATETIME NOT NULL COMMENT '创建时间',
    `updated_time` DATETIME NOT NULL COMMENT '更新时间',
    KEY `idx_dwd_org_stock_finance_info_org_id` (`org_id`),
    KEY `idx_dwd_org_stock_finance_info_stock_code` (`stock_code`),
    KEY `idx_dwd_org_stock_finance_info_external_id` (`external_id`),
    KEY `idx_dwd_org_stock_finance_info_occur_period` (`occur_period`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='上市企业主要财务指标';
