CREATE TABLE `dwd_scholar` (
  `id` bigint NOT NULL COMMENT '主键',
  `scholar_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '学者id',
  `name_en` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '英文姓名',
  `name_zh` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '中文姓名',
  `avatar` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '头像',
  `scholar_org_name_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '英文机构',
  `scholar_org_name_zh` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT '' COMMENT '中文机构',
  `scholar_org_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '所属机构id，学者所属机构id',
  `bio` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '个人简介/学术简介，学者的个人或学术简介信息',
  `bio_zh` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '个人简介/学术简介（中文），学者的中文个人或学术简介信息',
  `work_experience_en` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '工作经历英文（包含机构和职务）',
  `work_experience_zh` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '工作经历中文（包含机构和职务）',
  `education_background_en` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '教育背景（英文），学者的英文教育经历信息',
  `education_background_zh` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '教育背景（中文），学者的中文教育经历信息',
  `paper_nums` int NOT NULL DEFAULT '0' COMMENT '论文数量',
  `citation_nums` int NOT NULL DEFAULT '0' COMMENT '被引数量',
  `h_index` int NOT NULL DEFAULT '0' COMMENT 'H指数',
  `status` int NOT NULL DEFAULT '1' COMMENT '状态：0:无效,1:有效',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录最后更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='深势-学者表';
